### ISSUE TITLE
Use SQLite in dev and Postgres in prod

### ISSUE THREAD

**Issue by tedspare** [RubricLab/create-rubric-app#16]
Decoupled from #9 

Some context:
- We want to allow a demo to be deployed directly from **/templates/agent**
- Everything works (see [this demo](https://create-rubric-app.vercel.app/)) except for the DB since SQLite doesn't work in serverless (see [this comment](https://github.com/RubricLab/create-rubric-app/issues/9#issuecomment-1798781866))

Possible solution:
- Have two Prisma schemas eg. **prisma.schema** and **local.prisma.schema**
  - `provider="sqlite"` in the local schema and `provider="postgres"` in prod schema
- Run `prisma generate` and `prisma db push` on the right schema depending on env. This could be done in bash in **package.json** with `NODE_ENV` or we could just override the build command in Vercel (or any hosting platform) to `prisma generate --schema=./prisma/local.prisma.schema`

**Comment by tedspare** [comment]
@iamshanvy wanna take a crack at this? 👀

**Comment by iamshanvy** [comment]
where current postgres db is hosted?

to avoid dealing with different dbs [turso](https://turso.tech/) could be used to host sqlite for the demo, free tier will be enough here, might be simpler solution?

**Comment by DexterStorey** [comment]
Currently hosted on vercel postgres and it's part of our plan so the cost is negligible.

ITYJ (I trust your judgment) postgres or SQLite - whatever works, turso free tier could work but I wasn't able to set it up previously with turso super quick and gave up in favour of postgres - now I see this could be more overhead. Your call honestly if you're interested in taking this on, if not - no worries, no pressure 🧘 - can take a crack at it this weekend or colab on Gather (island.rubric.sh) any time. 🫡

**Comment by iamshanvy** [comment]
okie, I will look into this on Friday/Saturday this week if that's good, new Open AI toys created me a bunch of work till then 😂

**Comment by iamshanvy** [comment]
making turso work is surprisingly not straightforward 😂 I will spend some more time tomorrow, otherwise postgres it is, will update here

**Comment by iamshanvy** [comment]
uh oh `@libsql/client` library which is required to use `libsql (sqlite fork turso uses)` is having a separate packages for client and server, causing a need to have a separated instances of prisma db (as far as my testing goes), I believe switching between local sqlite and postgresql depending on env is a simpler solution, will start working on PR

**Comment by tedspare** [comment]
> making turso work is surprisingly not straightforward 😂 I will spend some more time tomorrow, otherwise postgres it is, will update here

honestly man, I heard it pitched as "sqlite in prod"

**Comment by tedspare** [comment]
Closed by #21
