### ISSUE TITLE
possibility to stream responses from agent

### ISSUE THREAD

**Issue by sahanxdissanayake** [RubricLab/create-rubric-app#4]
to recreate the issue:

ask for "Tell me 10 jokes"
expectation: each character to be streamed to the client

usecase: I want the user to be informed of what is happening on the backend(intermediate steps etc)

**Comment by tedspare** [comment]
@sahanxdissanayake want to give this a shot?

Two places to start would be in the [agent's streaming code](https://github.com/RubricLab/create-rubric-app/blob/main/templates/agent/src/agents/basic.ts#L19) and the [incoming stream code](https://github.com/RubricLab/create-rubric-app/blob/main/templates/agent/src/components/ChatBox.tsx#L54) in the ChatBox component.

Here for any questions or brainstorming if you do take it on 🙌

**Comment by arihanv** [comment]
Hey! I added some additional callbacks + client code to get detailed intermediate steps (function calls) back to the client. I got streaming to work on the client and am working on presenting the streamed response in one line. 

Will make a PR really soon! ⚡️
